# Стратегії гравців і їх корисність. Чисті і змішані стратегії. Рівновага в змішаних стратегіях.

---

## Визначення змішаних стратегій


> Змішана стратегія гравця $i$ з множиною стратегій $S_i$ позначається $\sigma_i \in [0,1]_{\mathbb{R}}^{|S_i|}$ та відповідає ймовірносному розподілу на просторі чистих стратегій.

Тобто виконується: 

$$
\sum_{i=1}^{|S_i|}\sigma_i = 1
$$

---

Очікуваний виграш гравця є мірою розподілу ймовірності.

---

## Обчислення корисності стратегії

Розглянемо гру 
$(A, B)\in\mathbb{{R^{m \times n}}^2}$, і нехай $\sigma_r$ та $\sigma_c$ - це змішані стратегії для першого і другого гравця відповідно. Тоді гравці отримають наступні виграші: 

$$
u_r(\sigma_r, \sigma_c) = \sum_{i=1}^m\sum_{j=1}^nA_{ij}{\sigma_r}_i{\sigma_c}_j
$$

та:

$$
u_c(\sigma_r, \sigma_c) = \sum_{i=1}^m\sum_{j=1}^nB_{ij}{\sigma_r}_i{\sigma_c}_j
$$

Це випливає з того, що:

- Ймовірність опинитись в певній клітинці  $A$ або $B$: ${\sigma_r}_i{\sigma_c}_j$
- Значення виграшу в клітинці дорівнює: $A_{ij}$ або $B_{ij}$

---

## Розглянемо декілька прикладів.

### Орлянка

Гра визначається наступними матрицями:

$$
A =
\begin{pmatrix}
    1 & -1\\
    -1 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -1 & 1\\
    1 & -1
\end{pmatrix}
$$

Проаналізуємо цю гру. Позначимо найкращі відповіді:

$$
A =
\begin{pmatrix}
    1^* & -1\\
    -1 & 1^*
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -1 & 1^*\\
    1^* & -1
\end{pmatrix}
$$

Отже рівноваги в чистих стратегіях немає. 

Припустимо, що гравці вибрали такі змішані стратегії:

$$
\sigma_r = (.2, .8)
\qquad
\sigma_c = (.6, .4)
$$

Тоді виграші будуть рівні:

$$
u_r(\sigma_r, \sigma_c) = 0.2 \times 0.6 \times 1 + 0.2 \times 0.4 \times (-1) + 0.8 \times 0.6 \times (-1) + 0.8 \times 0.4 \times 1=-0.12,
$$

$$
u_c(\sigma_r, \sigma_c) = 0.2 \times 0.6 \times (-1) + 0.2 \times 0.4 \times 1 + 0.8 \times 0.6 \times 1 + 0.8 \times 0.4 \times (-1)=0.12.
$$

---

### Гра лоббіювання

$$
A =
\begin{pmatrix}
    -5 & 25\\
    0 & 10
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -5 & 0\\
    15 & 10
\end{pmatrix}
$$

Знайти найкращі відповіді і рівноваги Неша.

---

## Лінійні перетворення

Зауважимо, що ми можемо перекомпонувати вирази для корисностей:

$$
u_r(\sigma_r, \sigma_c) = \sum_{i=1}^m{\sigma_r}_i\sum_{j=1}^nA_{ij}{\sigma_c}_j
$$

$$
u_c(\sigma_r, \sigma_c) = \sum_{i=1}^m{\sigma_r}_i\sum_{j=1}^nB_{ij}{\sigma_c}_j
$$

що, в свою чергу, приводить до наступного добутку матриць

$$
u_r(\sigma_r, \sigma_c) = {\sigma_r}A\sigma_c^T
$$

$$
u_c(\sigma_r, \sigma_c) = {\sigma_r}B\sigma_c^T
$$

Давайте перевіримо програмуванням.

In [11]:
import numpy as np
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])
sigma_r = np.array([.2, .8])
sigma_c = np.array([.6, .4])
np.dot(sigma_r, np.dot(A, sigma_c)), np.dot(sigma_r, np.dot(B, sigma_c))

sigma_r = np.array([.333, .666])
sigma_c = np.array([.666, .333])
np.dot(sigma_r, np.dot(A, sigma_c)), np.dot(sigma_r, np.dot(B, sigma_c))


(-0.11088900000000002, 0.11088900000000002)

Тепер використаємо nashpy

In [3]:
pip install nashpy

  Created wheel for nashpy: filename=nashpy-0.0.19-cp37-none-any.whl size=10814 sha256=46b62791f0c4a472bfb28e1deecba9ff7e29663f2bc81049276e9e7db3c5c88b
  Stored in directory: /Users/anymac/Library/Caches/pip/wheels/18/e9/56/2d04d01a6969d167f86d3afcb3d128c0b43d0d73ea471c835b
Successfully built nashpy
Note: you may need to restart the kernel to use updated packages.


In [4]:
import nashpy as nash
matching_pennies = nash.Game(A, B)
matching_pennies[sigma_r, sigma_c]

array([-0.12,  0.12])

In [ ]:
Заведемо гру лобіювання

In [36]:
import nashpy as nash
A = np.array([[-5, 25], [0, 10]])
B = np.array([[-5, 0], [15, 10]])
lobbying_game = nash.Game(A, B)
sigma_r = np.array([0.5, 0.5])
sigma_c = np.array([.75, .25])
lobbying_game[sigma_r, sigma_c]
game = nash.Game(A,B)
list(game.support_enumeration())

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.5, 0.5]), array([0.75, 0.25]))]

In [ ]:
Як пояснити цей результат?
Задачі.
1. Знайти рівновагу Неша в змішаних стратегіях в грі лобіювання. 

2. Завести і проаналізувати гру камінь-ножиці-папір. Знайти рівноваги. 

3. Завести гру з Теорії Великого Вибуху https://the-big-bang-theory.com/rock-paper-scissors-lizard-spock/ 
та спробувати знайти рівновагу.    
    


# Раціоналізація

---

## Визначення строго домінованої стратегії


В біматричній грі $(A, B)\in\mathbb{{R^{m \times n}}^2}$ стратегія $s$ називається _домінованою_ стратегією  $\bar s$, якщо для всіх стратегій іншого гравця $t$:

$$
u(s, t) < u(\bar s, t)
$$

---

Зокрема розглянемо дилему ув'язненого:

$$
A =
\begin{pmatrix}
    3 & 0\\
    5 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    3 & 5\\
    0 & 1
\end{pmatrix}
$$

- можна побачити, що $A_{2j} > A_{1j}$ для всіх $j$, отже перша стратегія першого гравця домінована по відношенню до другої.
- можна побачити, що $B_{i2} > B_{i1}$ для всіх $i$, отже перша стратегія другого гравця домінована по відношенню до другої.

---

## Слабо доміновані стратегії


В біматричній грі $(A, B)\in\mathbb{{R^{m \times n}}^2}$ стратегія $s$ називається _слабо домінованою_ стратегією  $\bar s$, якщо для всіх стратегій іншого гравця $t$:

$$
u(s, t) \leq u(\bar s, t)
$$

**та існує ** стратегія $t'$ така, що:

$$
u(s, t') < u(\bar s, t')
$$

---

Наприклад, розглянемо модифіковану версію попередньої гри:

$$
A =
\begin{pmatrix}
    3 & 0\\
    3 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    3 & 3\\
    0 & 1
\end{pmatrix}
$$

- видно, що $A_{2j} \geq A_{1j}$ для всіх $j$ **і** $A_{22} > A_{12}$, отже перша стратегія слабо домінована другою.
- видно, що $B_{i2} \geq B_{i1}$ для всіх $i$ **і** $B_{22} > B_{21}$, отже перша стратегія слабо домінована другою.

Перевіримо умови домінування


In [ ]:
import numpy as np
A = np.array([[3, 0], [3, 1]])
B = np.array([[3, 3], [0, 1]])

In [9]:
# Verify that first row is weakly dominated by second row
all(A[0,:] <= A[1,:]) and any(A[0,:] < A[1,:])

True

In [8]:
# Verify that first column is weakly dominated by second column
all(B[:,0] <= B[:,1]) and any(B[:,0] < B[:,1])

True

## Задачі

1. Splitting Pizza: You and a friend are in an Italian restaurant, and the owner offers both of you a free eight-slice pizza under the following condition. Each of you must simultaneously announce how many slices you would like; that is, each player i ∈ {1, 2} names his desired amount of pizza, 0 ≤ si ≤ 8. If s1 + s2 ≤ 8 then the players get their demands (and the owner eats any leftover slices). If s1 + s2 > 8, then the players get nothing. Assume that you each care only about how much pizza you individually consume, and the more the better.
    a. Write out or graph each player’s best-response correspondence.
    b. What outcomes can be supported as pure-strategy Nash equilibria?
    
2. Гра розміщення і її варіанти. 

In [7]:
import nashpy as nash
import numpy as np
A = np.array([[0.5, 0.9], [0.8, 0.3]])
B = np.array([[0.5, 0.1], [0.2, 0.7]])

game = nash.Game(A,B)
list(game.support_enumeration())

[(array([0.55555556, 0.44444444]), array([0.66666667, 0.33333333]))]